--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_STUDENT
--------------------------------------------------------

  CREATE TABLE "USER03"."TBL_STUDENT" 
   (	"SNO" VARCHAR2(8 BYTE), 
	"SNAME" VARCHAR2(10 BYTE), 
	"SYEAR" NUMBER(1,0), 
	"GENDER" VARCHAR2(3 BYTE), 
	"MAJOR" VARCHAR2(10 BYTE), 
	"SCORE" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into USER03.TBL_STUDENT
SET DEFINE OFF;
Insert into USER03.TBL_STUDENT (SNO,SNAME,SYEAR,GENDER,MAJOR,SCORE) values ('2001','이훈',2,'남','사복',84);
Insert into USER03.TBL_STUDENT (SNO,SNAME,SYEAR,GENDER,MAJOR,SCORE) values ('2002','맹구',2,'남','환공',99);
Insert into USER03.TBL_STUDENT (SNO,SNAME,SYEAR,GENDER,MAJOR,SCORE) values ('2003','김철수',2,'남','경영',88);
Insert into USER03.TBL_STUDENT (SNO,SNAME,SYEAR,GENDER,MAJOR,SCORE) values ('2004','신짱구',2,'남','수학',99);
Insert into USER03.TBL_STUDENT (SNO,SNAME,SYEAR,GENDER,MAJOR,SCORE) values ('2005','이유리',2,'여','사체',100);
Insert into USER03.TBL_STUDENT (SNO,SNAME,SYEAR,GENDER,MAJOR,SCORE) values ('2006','봉미선',4,'여','미술',87);
--------------------------------------------------------
--  DDL for Index SYS_C007083
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER03"."SYS_C007083" ON "USER03"."TBL_STUDENT" ("SNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "USER03"."TBL_STUDENT" ADD PRIMARY KEY ("SNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER03"."TBL_STUDENT" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "USER03"."TBL_STUDENT" MODIFY ("MAJOR" NOT NULL ENABLE);
  ALTER TABLE "USER03"."TBL_STUDENT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "USER03"."TBL_STUDENT" MODIFY ("SYEAR" NOT NULL ENABLE);
  ALTER TABLE "USER03"."TBL_STUDENT" MODIFY ("SNAME" NOT NULL ENABLE);
